module Compiler.Generate.MLIR.Patterns exposing (generateMonoPath, generateDTPath, generateChainCondition, testToTagInt, caseKindFromTest, computeFallbackTag)

{-| Pattern matching and path generation for MLIR code generation.

This module handles:

  - Path navigation (MonoPath and DT.Path)
  - Test generation for pattern matching
  - Case kind determination
  - Fallback tag computation

@docs generateMonoPath, generateDTPath, generateChainCondition, testToTagInt, caseKindFromTest, computeFallbackTag

-}

import Compiler.AST.Monomorphized as Mono
import Compiler.Data.Index as Index
import Compiler.Data.Name as Name
import Compiler.Generate.MLIR.Context as Ctx
import Compiler.Generate.MLIR.Intrinsics as Intrinsics
import Compiler.Generate.MLIR.Ops as Ops
import Compiler.Generate.MLIR.Types as Types
import Compiler.Optimize.Typed.DecisionTree as DT
import Mlir.Mlir exposing (MlirOp, MlirType(..))



-- ====== MONO PATH GENERATION ======


{-| Generate MLIR ops to navigate a MonoPath and extract a value.
-}
generateMonoPath : Ctx.Context -> Mono.MonoPath -> MlirType -> ( List MlirOp, String, Ctx.Context )
generateMonoPath ctx path targetType =
    case path of
        Mono.MonoRoot name ->
            let
                ( varName, _ ) =
                    Ctx.lookupVar ctx name
            in
            ( [], varName, ctx )

        Mono.MonoIndex index containerKind subPath ->
            let
                -- Navigate to the container object (always !eco.value)
                ( subOps, subVar, ctx1 ) =
                    generateMonoPath ctx subPath Types.ecoValue

                ( resultVar, ctx2 ) =
                    Ctx.freshVar ctx1

                -- Use type-specific projection ops based on ContainerKind.
                -- This ensures correct heap layout access for each container type.
                ( ctx3, projectOp ) =
                    case containerKind of
                        Mono.ListContainer ->
                            if index == 0 then
                                -- List head
                                Ops.ecoProjectListHead ctx2 resultVar targetType subVar

                            else
                                -- List tail (index 1)
                                Ops.ecoProjectListTail ctx2 resultVar subVar

                        Mono.Tuple2Container ->
                            Ops.ecoProjectTuple2 ctx2 resultVar index targetType subVar

                        Mono.Tuple3Container ->
                            Ops.ecoProjectTuple3 ctx2 resultVar index targetType subVar

                        Mono.CustomContainer ->
                            -- Type-specific projection for custom ADTs
                            Ops.ecoProjectCustom ctx2 resultVar index targetType subVar
            in
            ( subOps ++ [ projectOp ]
            , resultVar
            , ctx3
            )

        Mono.MonoField index subPath ->
            let
                -- Navigate to the container object (always !eco.value)
                ( subOps, subVar, ctx1 ) =
                    generateMonoPath ctx subPath Types.ecoValue

                ( resultVar, ctx2 ) =
                    Ctx.freshVar ctx1

                -- Project directly to the targetType using record projection.
                -- MonoField is generated from TOpt.Field which is record field access.
                -- Primitive types are stored unboxed and should be read directly.
                ( ctx3, projectOp ) =
                    Ops.ecoProjectRecord ctx2 resultVar index targetType subVar
            in
            ( subOps ++ [ projectOp ]
            , resultVar
            , ctx3
            )

        Mono.MonoUnbox subPath ->
            -- MonoUnbox is a SEMANTIC operation for single-constructor types.
            -- It means "unwrap the wrapper to access the inner value".
            -- This is a NO-OP in MLIR - the wrapped and unwrapped values have
            -- the same runtime representation (!eco.value).
            --
            -- NOTE: This is different from eco.unbox which converts !eco.value
            -- to a primitive type (i64, f64, etc.). eco.unbox is generated by
            -- MonoIndex when the targetType is a primitive, NOT by MonoUnbox.
            --
            -- By always passing through, we avoid generating incorrect sequences
            -- like: project -> eco.unbox -> project (where eco.unbox produces i64
            -- but the next project expects !eco.value).
            generateMonoPath ctx subPath targetType



-- ====== DECISION TREE PATH GENERATION ======


{-| Generate MLIR ops to navigate a DT.Path from the root scrutinee.

Returns the ops needed to project to the target, the result variable name,
and the updated context.

The targetType parameter specifies what type the final value should be:

  - For primitive tests (IsBool, IsInt, IsChr), this is the primitive type
  - For ctor tests, this is !eco.value

-}
generateDTPath : Ctx.Context -> Name.Name -> DT.Path -> MlirType -> ( List MlirOp, String, Ctx.Context )
generateDTPath ctx root dtPath targetType =
    case dtPath of
        DT.Empty ->
            -- The root is the scrutinee variable; look it up in varMappings.
            -- This correctly handles both boxed (!eco.value) and unboxed (i1, i64) parameters.
            let
                ( rootVar, rootTy ) =
                    Ctx.lookupVar ctx root
            in
            if rootTy == targetType then
                -- Already the right type (e.g. Bool param already i1)
                ( [], rootVar, ctx )

            else if Types.isEcoValueType rootTy && not (Types.isEcoValueType targetType) then
                -- Currently boxed, need primitive -> unbox and update mapping
                let
                    ( unboxOps, unboxedVar, ctx1 ) =
                        Intrinsics.unboxToType ctx rootVar targetType

                    -- Make future uses of root see the unboxed SSA value
                    ctx2 =
                        Ctx.addVarMapping root unboxedVar targetType ctx1
                in
                ( unboxOps, unboxedVar, ctx2 )

            else
                -- Types differ but we don't have a boxing rule here; just use rootVar.
                ( [], rootVar, ctx )

        DT.Index index hint subPath ->
            let
                -- Navigate to the container object (always !eco.value)
                ( subOps, subVar, ctx1 ) =
                    generateDTPath ctx root subPath Types.ecoValue

                ( resultVar, ctx2 ) =
                    Ctx.freshVar ctx1

                fieldIndex : Int
                fieldIndex =
                    Index.toMachine index

                -- Use type-specific projection ops based on ContainerHint.
                -- This ensures correct heap layout access for each container type.
                ( ctx3, projectOp ) =
                    case hint of
                        DT.HintList ->
                            if fieldIndex == 0 then
                                -- List head
                                Ops.ecoProjectListHead ctx2 resultVar targetType subVar

                            else
                                -- List tail (index 1)
                                Ops.ecoProjectListTail ctx2 resultVar subVar

                        DT.HintTuple2 ->
                            Ops.ecoProjectTuple2 ctx2 resultVar fieldIndex targetType subVar

                        DT.HintTuple3 ->
                            Ops.ecoProjectTuple3 ctx2 resultVar fieldIndex targetType subVar

                        DT.HintCustom ->
                            -- Custom ADTs (Maybe, Result, user types, big tuples)
                            Ops.ecoProjectCustom ctx2 resultVar fieldIndex targetType subVar

                        DT.HintUnknown ->
                            -- Fallback: treat like custom
                            Ops.ecoProjectCustom ctx2 resultVar fieldIndex targetType subVar
            in
            ( subOps ++ [ projectOp ], resultVar, ctx3 )

        DT.Unbox subPath ->
            -- DT.Unbox is a SEMANTIC operation for single-constructor types.
            -- It means "unwrap the wrapper to access the inner value".
            -- This is a NO-OP in MLIR - the wrapped and unwrapped values have
            -- the same runtime representation (!eco.value).
            --
            -- NOTE: This is different from eco.unbox which converts !eco.value
            -- to a primitive type (i64, f64, etc.). eco.unbox is generated by
            -- DT.Index when the targetType is a primitive, NOT by DT.Unbox.
            --
            -- By always passing through, we avoid generating incorrect sequences
            -- like: project -> eco.unbox -> project (where eco.unbox produces i64
            -- but the next project expects !eco.value).
            generateDTPath ctx root subPath targetType


{-| Generate MLIR ops to evaluate a DT.Test, returning a boolean result.

For constructor tests (IsCtor), we return the value to be tested with eco.case directly.
For other tests (IsBool, IsInt, etc.), we generate comparison ops that produce a boolean.

-}
generateTest : Ctx.Context -> Name.Name -> ( DT.Path, DT.Test ) -> ( List MlirOp, String, Ctx.Context )
generateTest ctx root ( path, test ) =
    let
        -- Determine target type based on the test
        targetType =
            case test of
                DT.IsCtor _ _ _ _ _ ->
                    Types.ecoValue

                DT.IsBool _ ->
                    I1

                DT.IsInt _ ->
                    I64

                DT.IsChr _ ->
                    Types.ecoChar

                DT.IsStr _ ->
                    Types.ecoValue

                DT.IsCons ->
                    Types.ecoValue

                DT.IsNil ->
                    Types.ecoValue

                DT.IsTuple ->
                    Types.ecoValue

        ( pathOps, valVar, ctx1 ) =
            generateDTPath ctx root path targetType
    in
    case test of
        DT.IsCtor _ _ index _ _ ->
            -- Produce a boolean (i1) by comparing the tag
            let
                expectedTag =
                    Index.toMachine index

                ( tagVar, ctx2 ) =
                    Ctx.freshVar ctx1

                ( ctx3, tagOp ) =
                    Ops.ecoGetTag ctx2 tagVar valVar

                ( constVar, ctx4 ) =
                    Ctx.freshVar ctx3

                ( ctx5, constOp ) =
                    Ops.arithConstantInt32 ctx4 constVar expectedTag

                ( resVar, ctx6 ) =
                    Ctx.freshVar ctx5

                ( ctx7, cmpOp ) =
                    Ops.arithCmpI ctx6 "eq" resVar ( tagVar, I32 ) ( constVar, I32 )
            in
            ( pathOps ++ [ tagOp, constOp, cmpOp ], resVar, ctx7 )

        DT.IsBool expected ->
            -- valVar is a Bool; if expected is False, invert it
            if expected then
                ( pathOps, valVar, ctx1 )

            else
                let
                    ( resVar, ctx2 ) =
                        Ctx.freshVar ctx1

                    -- Invert boolean: result = 1 - valVar (xor with 1)
                    ( constVar, ctx3 ) =
                        Ctx.freshVar ctx2

                    ( ctx4, constOp ) =
                        Ops.arithConstantBool ctx3 constVar True

                    ( ctx5, xorOp ) =
                        Ops.ecoBinaryOp ctx4 "arith.xori" resVar ( valVar, I1 ) ( constVar, I1 ) I1
                in
                ( pathOps ++ [ constOp, xorOp ], resVar, ctx5 )

        DT.IsInt i ->
            let
                ( constVar, ctx2 ) =
                    Ctx.freshVar ctx1

                ( ctx3, constOp ) =
                    Ops.arithConstantInt ctx2 constVar i

                ( resVar, ctx4 ) =
                    Ctx.freshVar ctx3

                ( ctx5, cmpOp ) =
                    Ops.ecoBinaryOp ctx4 "eco.int.eq" resVar ( valVar, I64 ) ( constVar, I64 ) I1
            in
            ( pathOps ++ [ constOp, cmpOp ], resVar, ctx5 )

        DT.IsChr c ->
            -- Compare character codes
            let
                charCode =
                    String.toList c |> List.head |> Maybe.map Char.toCode |> Maybe.withDefault 0

                ( constVar, ctx2 ) =
                    Ctx.freshVar ctx1

                ( ctx3, constOp ) =
                    Ops.arithConstantChar ctx2 constVar charCode

                ( resVar, ctx4 ) =
                    Ctx.freshVar ctx3

                ( ctx5, cmpOp ) =
                    Ops.ecoBinaryOp ctx4 "arith.cmpi" resVar ( valVar, Types.ecoChar ) ( constVar, Types.ecoChar ) I1
            in
            ( pathOps ++ [ constOp, cmpOp ], resVar, ctx5 )

        DT.IsStr s ->
            -- String comparison - use kernel function
            let
                ( strVar, ctx2 ) =
                    Ctx.freshVar ctx1

                -- Empty strings must use eco.constant EmptyString (invariant: never heap-allocated)
                ( ctx3, strOp ) =
                    if s == "" then
                        Ops.ecoConstantEmptyString ctx2 strVar

                    else
                        Ops.ecoStringLiteral ctx2 strVar s

                ( resVar, ctx4 ) =
                    Ctx.freshVar ctx3

                ( ctx5, cmpOp ) =
                    Ops.ecoCallNamed ctx4 resVar "Elm_Kernel_Utils_equal" [ ( valVar, Types.ecoValue ), ( strVar, Types.ecoValue ) ] I1
            in
            ( pathOps ++ [ strOp, cmpOp ], resVar, ctx5 )

        DT.IsCons ->
            -- Test if list is non-empty (tag == 1)
            let
                ( tagVar, ctx2 ) =
                    Ctx.freshVar ctx1

                ( ctx3, tagOp ) =
                    Ops.ecoGetTag ctx2 tagVar valVar

                ( constVar, ctx4 ) =
                    Ctx.freshVar ctx3

                ( ctx5, constOp ) =
                    Ops.arithConstantInt32 ctx4 constVar 1

                ( resVar, ctx6 ) =
                    Ctx.freshVar ctx5

                ( ctx7, cmpOp ) =
                    Ops.arithCmpI ctx6 "eq" resVar ( tagVar, I32 ) ( constVar, I32 )
            in
            ( pathOps ++ [ tagOp, constOp, cmpOp ], resVar, ctx7 )

        DT.IsNil ->
            -- Test if list is empty (tag == 0)
            let
                ( tagVar, ctx2 ) =
                    Ctx.freshVar ctx1

                ( ctx3, tagOp ) =
                    Ops.ecoGetTag ctx2 tagVar valVar

                ( constVar, ctx4 ) =
                    Ctx.freshVar ctx3

                ( ctx5, constOp ) =
                    Ops.arithConstantInt32 ctx4 constVar 0

                ( resVar, ctx6 ) =
                    Ctx.freshVar ctx5

                ( ctx7, cmpOp ) =
                    Ops.arithCmpI ctx6 "eq" resVar ( tagVar, I32 ) ( constVar, I32 )
            in
            ( pathOps ++ [ tagOp, constOp, cmpOp ], resVar, ctx7 )

        DT.IsTuple ->
            -- Tuples always match (we just need the value)
            let
                ( resVar, ctx2 ) =
                    Ctx.freshVar ctx1

                ( ctx3, constOp ) =
                    Ops.arithConstantBool ctx2 resVar True
            in
            ( pathOps ++ [ constOp ], resVar, ctx3 )


{-| Generate the condition for a Chain node by ANDing all test booleans.
-}
generateChainCondition : Ctx.Context -> Name.Name -> List ( DT.Path, DT.Test ) -> ( List MlirOp, String, Ctx.Context )
generateChainCondition ctx root tests =
    case tests of
        [] ->
            -- No tests means always true
            let
                ( resVar, ctx1 ) =
                    Ctx.freshVar ctx

                ( ctx2, constOp ) =
                    Ops.arithConstantBool ctx1 resVar True
            in
            ( [ constOp ], resVar, ctx2 )

        [ singleTest ] ->
            generateTest ctx root singleTest

        firstTest :: restTests ->
            let
                ( firstOps, firstVar, ctx1 ) =
                    generateTest ctx root firstTest

                ( restOps, restVar, ctx2 ) =
                    generateChainCondition ctx1 root restTests

                ( resVar, ctx3 ) =
                    Ctx.freshVar ctx2

                ( ctx4, andOp ) =
                    Ops.ecoBinaryOp ctx3 "arith.andi" resVar ( firstVar, I1 ) ( restVar, I1 ) I1
            in
            ( firstOps ++ restOps ++ [ andOp ], resVar, ctx4 )


{-| Get the tag from a DT.Test for use with eco.case
-}
testToTagInt : DT.Test -> Int
testToTagInt test =
    case test of
        DT.IsCtor _ _ index _ _ ->
            Index.toMachine index

        DT.IsCons ->
            1

        DT.IsNil ->
            0

        DT.IsBool True ->
            1

        DT.IsBool False ->
            0

        DT.IsInt i ->
            i

        DT.IsChr c ->
            String.toList c |> List.head |> Maybe.map Char.toCode |> Maybe.withDefault 0

        DT.IsStr _ ->
            0

        DT.IsTuple ->
            0


{-| Determine the case kind from a DT.Test for use with eco.case.

Returns a string indicating how the runtime should handle the case:

  - "ctor" for ADT constructor matching (uses GetTagOp)
  - "int" for integer matching (unboxes to i64 and compares)
  - "chr" for character matching (unboxes to i16 and compares)
  - "str" for string matching (uses string comparison)

-}
caseKindFromTest : DT.Test -> String
caseKindFromTest test =
    case test of
        DT.IsCtor _ _ _ _ _ ->
            "ctor"

        DT.IsCons ->
            "ctor"

        DT.IsNil ->
            "ctor"

        DT.IsBool _ ->
            "ctor"

        DT.IsInt _ ->
            "int"

        DT.IsChr _ ->
            "chr"

        DT.IsStr _ ->
            "str"

        DT.IsTuple ->
            "ctor"


{-| Compute the fallback tag for a fan-out based on the edge tests.
For two-way branches (Bool, Cons/Nil), this computes the "other" tag.
For N-way branches (custom types), this finds the first missing tag.
-}
computeFallbackTag : List DT.Test -> Int
computeFallbackTag edgeTests =
    case edgeTests of
        [ DT.IsBool True ] ->
            0

        [ DT.IsBool False ] ->
            1

        [ DT.IsCons ] ->
            0

        [ DT.IsNil ] ->
            1

        _ ->
            -- For custom types with multiple edges, find the first unused tag
            let
                usedTags =
                    List.map testToTagInt edgeTests

                maxTag =
                    List.maximum usedTags |> Maybe.withDefault 0
            in
            -- Find first unused tag from 0 to maxTag+1
            List.range 0 (maxTag + 1)
                |> List.filter (\t -> not (List.member t usedTags))
                |> List.head
                |> Maybe.withDefault (maxTag + 1)
