// RUN: %ecoc %s -emit=jit 2>&1 | %FileCheck %s
//
// Test basic Maybe Just/Nothing case pattern.
// This tests the canonical case expression pattern generated by Elm.
// Updated for eco.case as terminator: each case must be in its own function.

module {
  // Helper function: case on Maybe, return inner value or default
  func.func private @extract_maybe(%maybe: !eco.value, %default: !eco.value) -> !eco.value {
    eco.case %maybe : !eco.value [0, 1] result_types [!eco.value] {
      // Nothing case: return default
      eco.return %default : !eco.value
    }, {
      // Just case: extract and return the value
      %inner = eco.project.custom %maybe[0] : !eco.value -> !eco.value
      eco.return %inner : !eco.value
    } {case_kind = "ctor"}
  }

  func.func @main() -> i64 {
    %c0 = arith.constant 0 : i64
    %c42 = arith.constant 42 : i64
    %c99 = arith.constant 99 : i64

    // Create Maybe.Just 42
    %b42 = eco.box %c42 : i64 -> !eco.value
    %just = eco.construct.custom(%b42) {tag = 1 : i64, size = 1 : i64} : (!eco.value) -> !eco.value

    // Create Maybe.Nothing
    %nothing = eco.construct.custom() {tag = 0 : i64, size = 0 : i64} : () -> !eco.value

    // Default value
    %b99 = eco.box %c99 : i64 -> !eco.value

    // Test 1: Case on Just - should take tag 1 branch and return inner value (42)
    %result1 = func.call @extract_maybe(%just, %b99) : (!eco.value, !eco.value) -> !eco.value
    eco.dbg %result1 : !eco.value
    // CHECK: 42

    // Test 2: Case on Nothing - should take tag 0 branch and return default (99)
    %result2 = func.call @extract_maybe(%nothing, %b99) : (!eco.value, !eco.value) -> !eco.value
    eco.dbg %result2 : !eco.value
    // CHECK: 99

    return %c0 : i64
  }
}
