// RUN: %ecoc %s -emit=jit 2>&1 | %FileCheck %s
//
// Test basic Maybe Just/Nothing case pattern.
// This tests the canonical case expression pattern generated by Elm.

module {
  func.func @main() -> i64 {
    %c0 = arith.constant 0 : i64
    %c42 = arith.constant 42 : i64
    %c99 = arith.constant 99 : i64

    // Create Maybe.Just 42
    %b42 = eco.box %c42 : i64 -> !eco.value
    %just = eco.construct.custom(%b42) {tag = 1 : i64, size = 1 : i64} : (!eco.value) -> !eco.value

    // Create Maybe.Nothing
    %nothing = eco.construct.custom() {tag = 0 : i64, size = 0 : i64} : () -> !eco.value

    // Test 1: Case on Just - should take tag 1 branch and print inner value
    eco.case %just : !eco.value [0, 1] result_types [!eco.value] {
      // Nothing case: return default
      %default = eco.box %c99 : i64 -> !eco.value
      eco.dbg %default : !eco.value
      eco.return %default : !eco.value
    }, {
      // Just case: extract and return the value
      %inner = eco.project.custom %just[0] : !eco.value -> !eco.value
      eco.dbg %inner : !eco.value
      eco.return %inner : !eco.value
    } {case_kind = "ctor"}
    // CHECK: 42

    // Test 2: Case on Nothing - should take tag 0 branch and print default
    eco.case %nothing : !eco.value [0, 1] result_types [!eco.value] {
      // Nothing case: return default
      %default = eco.box %c99 : i64 -> !eco.value
      eco.dbg %default : !eco.value
      eco.return %default : !eco.value
    }, {
      // Just case: would extract value (but won't be reached)
      %inner = eco.project.custom %nothing[0] : !eco.value -> !eco.value
      eco.dbg %inner : !eco.value
      eco.return %inner : !eco.value
    } {case_kind = "ctor"}
    // CHECK: 99

    return %c0 : i64
  }
}
