// RUN: %ecoc %s -emit=jit 2>&1 | %FileCheck %s
//
// Test papCreate with unboxed captured values (i64, f64).

module {
  // Typed function that adds three ints.
  // The wrapper auto-generated by getOrCreateWrapper handles
  // HPointer unboxing for each parameter.
  func.func @add_three_ints(%a: i64, %b: i64, %c: i64) -> i64 {
    %sum1 = eco.int.add %a, %b : i64
    %result = eco.int.add %sum1, %c : i64
    eco.return %result : i64
  }

  func.func @main() -> i64 {
    // Create unboxed integers to capture
    %i10 = arith.constant 10 : i64
    %i20 = arith.constant 20 : i64

    // Create PAP with two unboxed captured values
    // arity = 3 (2 captured + 1 remaining)
    // unboxed_bitmap = 0b11 = 3 (both captures are i64)
    %pap = "eco.papCreate"(%i10, %i20) {
      function = @add_three_ints,
      arity = 3 : i64,
      num_captured = 2 : i64,
      unboxed_bitmap = 3 : i64
    } : (i64, i64) -> !eco.value
    eco.dbg %pap : !eco.value
    // CHECK: <fn>

    // Call with remaining arg (unboxed i64, same as function parameter type)
    %i5 = arith.constant 5 : i64

    %result = "eco.papExtend"(%pap, %i5) {
      remaining_arity = 1 : i64,
      newargs_unboxed_bitmap = 1 : i64
    } : (!eco.value, i64) -> i64
    // Expected: 10 + 20 + 5 = 35
    eco.dbg %result : i64
    // CHECK: [eco.dbg] 35

    // Test with different captured values
    %i100 = arith.constant 100 : i64
    %i200 = arith.constant 200 : i64
    %pap2 = "eco.papCreate"(%i100, %i200) {
      function = @add_three_ints,
      arity = 3 : i64,
      num_captured = 2 : i64,
      unboxed_bitmap = 3 : i64
    } : (i64, i64) -> !eco.value

    %i50 = arith.constant 50 : i64

    %result2 = "eco.papExtend"(%pap2, %i50) {
      remaining_arity = 1 : i64,
      newargs_unboxed_bitmap = 1 : i64
    } : (!eco.value, i64) -> i64
    // Expected: 100 + 200 + 50 = 350
    eco.dbg %result2 : i64
    // CHECK: [eco.dbg] 350

    %zero = arith.constant 0 : i64
    return %zero : i64
  }
}
