// RUN: %ecoc %s -emit=jit 2>&1 | %FileCheck %s
//
// Test papExtend with typed (unboxed) arguments that saturate the closure.
// This tests the typed closure ABI where arguments are passed in their actual
// SSA types rather than boxed to !eco.value.

module {
  // Typed function that doubles an integer.
  // The wrapper auto-generated by getOrCreateWrapper handles HPointer unboxing.
  func.func @double(%x: i64) -> i64 {
    %result = eco.int.add %x, %x : i64
    eco.return %result : i64
  }

  func.func @main() -> i64 {
    %c42 = arith.constant 42 : i64

    // Create PAP with no captured args, arity 1
    %pap = "eco.papCreate"() {
      function = @double,
      arity = 1 : i64,
      num_captured = 0 : i64,
      unboxed_bitmap = 0 : i64
    } : () -> !eco.value

    // Extend with typed (unboxed) i64 argument - should saturate and return i64
    // newargs_unboxed_bitmap = 1 indicates arg 0 is unboxed
    %result = "eco.papExtend"(%pap, %c42) {
      remaining_arity = 1 : i64,
      newargs_unboxed_bitmap = 1 : i64
    } : (!eco.value, i64) -> i64

    eco.dbg %result : i64
    // CHECK: 84

    %zero = arith.constant 0 : i64
    return %zero : i64
  }
}
