module Compiler.Generate.CodeGen.MLIR exposing (backend)

import Compiler.AST.Optimized as Opt
import Compiler.Data.Index as Index
import Compiler.Data.Name as Name
import Compiler.Elm.ModuleName as ModuleName
import Compiler.Generate.CodeGen as CodeGen
import Compiler.Generate.Mode as Mode
import Compiler.Reporting.Annotation as A
import Data.Map as Dict
import Data.Set as EverySet exposing (EverySet)
import System.TypeCheck.IO as IO
import Utils.Main as Utils



-- BACKEND


backend : CodeGen.CodeGen
backend =
    { generate =
        \config ->
            CodeGen.TextOutput <|
                generateModule config.mode config.graph config.mains
    , generateForRepl =
        \_ ->
            -- MLIR REPL would need compilation + execution
            CodeGen.TextOutput "// MLIR REPL not yet implemented\n"
    , generateForReplEndpoint =
        \_ ->
            CodeGen.TextOutput "// MLIR REPL endpoint not yet implemented\n"
    }



-- STATE
-- Tracks which globals have been generated (for dead code elimination)


type State
    = State String (EverySet (List String) Opt.Global)


emptyState : State
emptyState =
    State "" EverySet.empty


stateToString : State -> String
stateToString (State builder _) =
    builder


addOutput : String -> State -> State
addOutput code (State builder seen) =
    State (builder ++ code) seen


hasSeen : Opt.Global -> State -> Bool
hasSeen global (State _ seen) =
    EverySet.member Opt.toComparableGlobal global seen


markSeen : Opt.Global -> State -> State
markSeen global (State builder seen) =
    State builder (EverySet.insert Opt.toComparableGlobal global seen)



-- CONTEXT
-- The context tracks SSA variable numbering and other state during expression generation


type alias Context =
    { nextVar : Int
    , indent : Int
    , mode : Mode.Mode
    }


initContext : Mode.Mode -> Context
initContext mode =
    { nextVar = 0
    , indent = 1
    , mode = mode
    }


freshVar : Context -> ( String, Context )
freshVar ctx =
    ( "%" ++ String.fromInt ctx.nextVar
    , { ctx | nextVar = ctx.nextVar + 1 }
    )


indent : Context -> Context
indent ctx =
    { ctx | indent = ctx.indent + 1 }


pad : Context -> String
pad ctx =
    String.repeat ctx.indent "  "



-- GENERATE MODULE


generateModule : Mode.Mode -> Opt.GlobalGraph -> CodeGen.Mains -> String
generateModule mode ((Opt.GlobalGraph graph _) as globalGraph) mains =
    let
        header : String
        header =
            "// Generated by Guida MLIR backend (eco dialect)\n"
                ++ "// Target: eco-runtime\n\n"
                ++ "module {\n"

        footer : String
        footer =
            "}\n"

        -- Start from mains and recursively add only reachable globals (dead code elimination)
        state : State
        state =
            Dict.foldr ModuleName.compareCanonical (addMain mode graph) emptyState mains
    in
    header ++ stateToString state ++ footer


addMain : Mode.Mode -> Graph -> IO.Canonical -> Opt.Main -> State -> State
addMain mode graph home main state =
    let
        mainGlobal : Opt.Global
        mainGlobal =
            Opt.Global home "main"

        stateWithMain : State
        stateWithMain =
            addGlobal mode graph mainGlobal state

        ctx : Context
        ctx =
            initContext mode
    in
    case main of
        Opt.Static ->
            addOutput
                ("\n  // Static main entry point\n"
                    ++ "  func.func @"
                    ++ canonicalToMLIRName home
                    ++ "_main() -> !eco.value {\n"
                    ++ "    %main_val = \"eco.call\"() {function = @\""
                    ++ canonicalToMLIRName home
                    ++ "_main\", musttail = false} : () -> !eco.value\n"
                    ++ "    \"eco.return\"(%main_val) : (!eco.value) -> ()\n"
                    ++ "  }\n"
                )
                stateWithMain

        Opt.Dynamic _ flagsDecoder ->
            let
                ( decoderCode, decoderVar, _ ) =
                    generateExpr ctx flagsDecoder
            in
            addOutput
                ("\n  // Dynamic main entry point (with flags decoder)\n"
                    ++ "  func.func @"
                    ++ canonicalToMLIRName home
                    ++ "_main() -> !eco.value {\n"
                    ++ decoderCode
                    ++ "    // TODO: Initialize Elm runtime with flags decoder\n"
                    ++ "    %main_val = \"eco.call\"("
                    ++ decoderVar
                    ++ ") {function = @\"Elm_Platform_initialize\", musttail = false} : (!eco.value) -> !eco.value\n"
                    ++ "    \"eco.return\"(%main_val) : (!eco.value) -> ()\n"
                    ++ "  }\n"
                )
                stateWithMain


addGlobal : Mode.Mode -> Graph -> Opt.Global -> State -> State
addGlobal mode graph global state =
    if hasSeen global state then
        state

    else
        addGlobalHelp mode graph global (markSeen global state)


addGlobalHelp : Mode.Mode -> Graph -> Opt.Global -> State -> State
addGlobalHelp mode graph ((Opt.Global home name) as global) state =
    let
        addDeps : EverySet (List String) Opt.Global -> State -> State
        addDeps deps someState =
            let
                sortedDeps : List Opt.Global
                sortedDeps =
                    List.sortWith Opt.compareGlobal (EverySet.toList Opt.compareGlobal deps)
            in
            List.foldl (\dep st -> addGlobal mode graph dep st) someState sortedDeps

        funcName : String
        funcName =
            globalToMLIRName global

        ctx : Context
        ctx =
            initContext mode
    in
    case Utils.find Opt.toComparableGlobal global graph of
        Opt.Define expr deps ->
            addOutput (generateTopLevelDefWithHeader ctx funcName "Define" expr) (addDeps deps state)

        Opt.TrackedDefine _ expr deps ->
            addOutput (generateTopLevelDefWithHeader ctx funcName "TrackedDefine" expr) (addDeps deps state)

        Opt.DefineTailFunc _ argNames body deps ->
            addOutput (generateTailFuncWithHeader ctx funcName argNames body) (addDeps deps state)

        Opt.Ctor index arity ->
            addOutput (generateCtorFuncWithHeader ctx funcName index arity) state

        Opt.Enum index ->
            addOutput (generateEnumConstantWithHeader ctx funcName index) state

        Opt.Box ->
            addOutput (generateBoxFuncWithHeader ctx funcName) state

        Opt.Link linkedGlobal ->
            addOutput ("\n  // Link: " ++ funcName ++ " -> " ++ globalToMLIRName linkedGlobal ++ "\n") <|
                addGlobal mode graph linkedGlobal state

        Opt.Cycle names values funcs deps ->
            addOutput
                ("\n  // TODO: Cycle with "
                    ++ String.fromInt (List.length names)
                    ++ " mutually recursive definitions\n"
                    ++ "  // Names: "
                    ++ String.join ", " names
                    ++ "\n"
                )
                (addDeps deps state)

        Opt.Manager effectsType ->
            addOutput ("\n  // TODO: Effects Manager (" ++ effectsTypeToString effectsType ++ ")\n") state

        Opt.Kernel chunks deps ->
            addOutput
                ("\n  // TODO: Kernel code with "
                    ++ String.fromInt (List.length chunks)
                    ++ " chunks\n"
                )
                (addDeps deps state)

        Opt.PortIncoming _ deps ->
            addOutput ("\n  // TODO: PortIncoming: " ++ funcName ++ "\n") (addDeps deps state)

        Opt.PortOutgoing _ deps ->
            addOutput ("\n  // TODO: PortOutgoing: " ++ funcName ++ "\n") (addDeps deps state)



effectsTypeToString : Opt.EffectsType -> String
effectsTypeToString effectsType =
    case effectsType of
        Opt.Cmd ->
            "Cmd"

        Opt.Sub ->
            "Sub"

        Opt.Fx ->
            "Cmd+Sub"



-- GENERATE TOP-LEVEL DEFINITION


generateTopLevelDefWithHeader : Context -> String -> String -> Opt.Expr -> String
generateTopLevelDefWithHeader ctx funcName nodeType expr =
    "\n  // " ++ nodeType ++ ": " ++ funcName ++ "\n" ++ generateTopLevelDef ctx funcName expr


generateTopLevelDef : Context -> String -> Opt.Expr -> String
generateTopLevelDef ctx funcName expr =
    case expr of
        Opt.Function args body ->
            generateFuncDef ctx funcName args body

        Opt.TrackedFunction locatedArgs body ->
            generateFuncDef ctx funcName (List.map A.toValue locatedArgs) body

        _ ->
            -- Value (thunk) - wrap in nullary function
            let
                ( bodyCode, resultVar, _ ) =
                    generateExpr ctx expr
            in
            "  func.func @"
                ++ funcName
                ++ "() -> !eco.value {\n"
                ++ bodyCode
                ++ "    \"eco.return\"("
                ++ resultVar
                ++ ") : (!eco.value) -> ()\n"
                ++ "  }\n"


generateFuncDef : Context -> String -> List Name.Name -> Opt.Expr -> String
generateFuncDef ctx funcName args body =
    let
        argList : String
        argList =
            args
                |> List.indexedMap (\i name -> "%" ++ name ++ ": !eco.value")
                |> String.join ", "

        -- Create context with args already bound
        ctxWithArgs : Context
        ctxWithArgs =
            { ctx | nextVar = List.length args }

        ( bodyCode, resultVar, _ ) =
            generateExpr ctxWithArgs body
    in
    "  func.func @"
        ++ funcName
        ++ "("
        ++ argList
        ++ ") -> !eco.value {\n"
        ++ bodyCode
        ++ "    \"eco.return\"("
        ++ resultVar
        ++ ") : (!eco.value) -> ()\n"
        ++ "  }\n"


generateTailFuncWithHeader : Context -> String -> List (A.Located Name.Name) -> Opt.Expr -> String
generateTailFuncWithHeader ctx funcName locatedArgs body =
    "\n  // DefineTailFunc: " ++ funcName ++ "\n" ++ generateTailFunc ctx funcName locatedArgs body


generateTailFunc : Context -> String -> List (A.Located Name.Name) -> Opt.Expr -> String
generateTailFunc ctx funcName locatedArgs body =
    let
        args : List Name.Name
        args =
            List.map A.toValue locatedArgs

        argList : String
        argList =
            args
                |> List.indexedMap (\i name -> "%" ++ name ++ ": !eco.value")
                |> String.join ", "

        ctxWithArgs : Context
        ctxWithArgs =
            { ctx | nextVar = List.length args }

        ( bodyCode, resultVar, _ ) =
            generateExpr ctxWithArgs body
    in
    "  // Tail-recursive function with joinpoint\n"
        ++ "  func.func @"
        ++ funcName
        ++ "("
        ++ argList
        ++ ") -> !eco.value {\n"
        ++ "    \"eco.joinpoint\"() ({\n"
        ++ "    ^entry("
        ++ String.join ", " (List.map (\n -> "%" ++ n ++ "_loop: !eco.value") args)
        ++ "):\n"
        ++ bodyCode
        ++ "      \"eco.return\"("
        ++ resultVar
        ++ ") : (!eco.value) -> ()\n"
        ++ "    }, {\n"
        ++ "      \"eco.jump\"("
        ++ String.join ", " (List.map (\n -> "%" ++ n) args)
        ++ ") {join_point = 0} : ("
        ++ String.join ", " (List.map (\_ -> "!eco.value") args)
        ++ ") -> ()\n"
        ++ "    }) {id = 0} : () -> ()\n"
        ++ "  }\n"


generateCtorFuncWithHeader : Context -> String -> Index.ZeroBased -> Int -> String
generateCtorFuncWithHeader ctx funcName index arity =
    "\n  // Ctor: "
        ++ funcName
        ++ " (tag="
        ++ String.fromInt (Index.toMachine index)
        ++ ", arity="
        ++ String.fromInt arity
        ++ ")\n"
        ++ generateCtorFunc ctx funcName index arity


generateCtorFunc : Context -> String -> Index.ZeroBased -> Int -> String
generateCtorFunc ctx funcName index arity =
    if arity == 0 then
        -- Nullary constructor - return constant
        let
            tag : Int
            tag =
                Index.toMachine index
        in
        "  func.func @"
            ++ funcName
            ++ "() -> !eco.value {\n"
            ++ "    %result = \"eco.construct\"() {constructor = @\""
            ++ funcName
            ++ "\", tag = "
            ++ String.fromInt tag
            ++ " : i64, size = 0 : i64} : () -> !eco.value\n"
            ++ "    \"eco.return\"(%result) : (!eco.value) -> ()\n"
            ++ "  }\n"

    else
        -- Constructor with arguments - generate curried function
        let
            tag : Int
            tag =
                Index.toMachine index

            argNames : List String
            argNames =
                List.range 0 (arity - 1)
                    |> List.map (\i -> "arg" ++ String.fromInt i)

            argList : String
            argList =
                argNames
                    |> List.map (\n -> "%" ++ n ++ ": !eco.value")
                    |> String.join ", "

            argRefs : String
            argRefs =
                argNames
                    |> List.map (\n -> "%" ++ n)
                    |> String.join ", "

            argTypes : String
            argTypes =
                List.repeat arity "!eco.value"
                    |> String.join ", "
        in
        "  func.func @"
            ++ funcName
            ++ "("
            ++ argList
            ++ ") -> !eco.value {\n"
            ++ "    %result = \"eco.construct\"("
            ++ argRefs
            ++ ") {constructor = @\""
            ++ funcName
            ++ "\", tag = "
            ++ String.fromInt tag
            ++ " : i64, size = "
            ++ String.fromInt arity
            ++ " : i64} : ("
            ++ argTypes
            ++ ") -> !eco.value\n"
            ++ "    \"eco.return\"(%result) : (!eco.value) -> ()\n"
            ++ "  }\n"


generateEnumConstantWithHeader : Context -> String -> Index.ZeroBased -> String
generateEnumConstantWithHeader ctx funcName index =
    "\n  // Enum: "
        ++ funcName
        ++ " (tag="
        ++ String.fromInt (Index.toMachine index)
        ++ ")\n"
        ++ generateEnumConstant ctx funcName index


generateEnumConstant : Context -> String -> Index.ZeroBased -> String
generateEnumConstant ctx funcName index =
    let
        tag : Int
        tag =
            Index.toMachine index
    in
    "  func.func @"
        ++ funcName
        ++ "() -> !eco.value {\n"
        ++ "    %result = \"eco.construct\"() {constructor = @\""
        ++ funcName
        ++ "\", tag = "
        ++ String.fromInt tag
        ++ " : i64, size = 0 : i64} : () -> !eco.value\n"
        ++ "    \"eco.return\"(%result) : (!eco.value) -> ()\n"
        ++ "  }\n"


generateBoxFuncWithHeader : Context -> String -> String
generateBoxFuncWithHeader ctx funcName =
    "\n  // Box: " ++ funcName ++ " (identity wrapper)\n" ++ generateBoxFunc ctx funcName


generateBoxFunc : Context -> String -> String
generateBoxFunc ctx funcName =
    -- Box is identity - just return the argument
    "  func.func @"
        ++ funcName
        ++ "(%arg0: !eco.value) -> !eco.value {\n"
        ++ "    \"eco.return\"(%arg0) : (!eco.value) -> ()\n"
        ++ "  }\n"



-- GENERATE EXPRESSION
-- Returns (code, resultVar, updatedContext)


generateExpr : Context -> Opt.Expr -> ( String, String, Context )
generateExpr ctx expr =
    let
        p : String
        p =
            pad ctx
    in
    case expr of
        ------------------------------------------
        -- LITERALS (Easy)
        ------------------------------------------
        Opt.Bool _ value ->
            let
                ( var, ctx1 ) =
                    freshVar ctx

                tag : Int
                tag =
                    if value then
                        1

                    else
                        0

                ctorName : String
                ctorName =
                    if value then
                        "Basics_True"

                    else
                        "Basics_False"
            in
            ( p
                ++ var
                ++ " = \"eco.construct\"() {constructor = @\""
                ++ ctorName
                ++ "\", tag = "
                ++ String.fromInt tag
                ++ " : i64, size = 0 : i64} : () -> !eco.value\n"
            , var
            , ctx1
            )

        Opt.Chr _ value ->
            let
                ( var, ctx1 ) =
                    freshVar ctx

                -- Get first char code (simplified - doesn't handle all Unicode)
                charCode : Int
                charCode =
                    String.uncons value
                        |> Maybe.map (Tuple.first >> Char.toCode)
                        |> Maybe.withDefault 0
            in
            ( p
                ++ var
                ++ " = \"eco.construct\"(%charcode) {constructor = @\"Char\", tag = 0 : i64, size = 1 : i64} : (!eco.value) -> !eco.value\n"
                ++ p
                ++ "// TODO: Proper char literal for: "
                ++ escapeString value
                ++ " (code="
                ++ String.fromInt charCode
                ++ ")\n"
            , var
            , ctx1
            )

        Opt.Str _ value ->
            let
                ( var, ctx1 ) =
                    freshVar ctx
            in
            ( p
                ++ var
                ++ " = \"eco.string_literal\"() {value = "
                ++ escapeString value
                ++ "} : () -> !eco.value\n"
            , var
            , ctx1
            )

        Opt.Int _ value ->
            let
                ( var, ctx1 ) =
                    freshVar ctx
            in
            ( p
                ++ "// Int literal: "
                ++ String.fromInt value
                ++ "\n"
                ++ p
                ++ var
                ++ " = arith.constant "
                ++ String.fromInt value
                ++ " : i64\n"
                ++ p
                ++ "// TODO: Box integer if needed\n"
            , var
            , ctx1
            )

        Opt.Float _ value ->
            let
                ( var, ctx1 ) =
                    freshVar ctx
            in
            ( p
                ++ "// Float literal: "
                ++ String.fromFloat value
                ++ "\n"
                ++ p
                ++ var
                ++ " = arith.constant "
                ++ String.fromFloat value
                ++ " : f64\n"
                ++ p
                ++ "// TODO: Box float if needed\n"
            , var
            , ctx1
            )

        ------------------------------------------
        -- VARIABLES (Easy)
        ------------------------------------------
        Opt.VarLocal name ->
            -- Reference to local variable - just use its SSA name
            ( "", "%" ++ name, ctx )

        Opt.TrackedVarLocal _ name ->
            ( "", "%" ++ name, ctx )

        Opt.VarGlobal _ global ->
            -- Reference to top-level definition - call it
            let
                ( var, ctx1 ) =
                    freshVar ctx

                globalName : String
                globalName =
                    globalToMLIRName global
            in
            ( p
                ++ var
                ++ " = \"eco.call\"() {function = @\""
                ++ globalName
                ++ "\", musttail = false} : () -> !eco.value\n"
            , var
            , ctx1
            )

        Opt.VarEnum _ global index ->
            -- Enum constructor - just an integer tag
            let
                ( var, ctx1 ) =
                    freshVar ctx

                tag : Int
                tag =
                    Index.toMachine index
            in
            ( p
                ++ var
                ++ " = \"eco.construct\"() {constructor = @\""
                ++ globalToMLIRName global
                ++ "\", tag = "
                ++ String.fromInt tag
                ++ " : i64, size = 0 : i64} : () -> !eco.value\n"
            , var
            , ctx1
            )

        Opt.VarBox _ global ->
            -- Box constructor - identity function, just reference it
            let
                ( var, ctx1 ) =
                    freshVar ctx
            in
            ( p
                ++ var
                ++ " = \"eco.call\"() {function = @\""
                ++ globalToMLIRName global
                ++ "\", musttail = false} : () -> !eco.value\n"
            , var
            , ctx1
            )

        Opt.VarCycle _ home name ->
            let
                ( var, ctx1 ) =
                    freshVar ctx

                cycleName : String
                cycleName =
                    canonicalToMLIRName home ++ "_" ++ name
            in
            ( p
                ++ "// TODO: VarCycle reference to mutually recursive binding\n"
                ++ p
                ++ var
                ++ " = \"eco.call\"() {function = @\""
                ++ cycleName
                ++ "\", musttail = false} : () -> !eco.value\n"
            , var
            , ctx1
            )

        Opt.VarDebug _ name home maybeName ->
            let
                ( var, ctx1 ) =
                    freshVar ctx
            in
            ( p
                ++ "// Debug."
                ++ name
                ++ "\n"
                ++ p
                ++ var
                ++ " = \"eco.dbg\"() : () -> !eco.value  // TODO: implement Debug."
                ++ name
                ++ "\n"
            , var
            , ctx1
            )

        Opt.VarKernel _ home name ->
            let
                ( var, ctx1 ) =
                    freshVar ctx

                kernelName : String
                kernelName =
                    "Elm_Kernel_" ++ home ++ "_" ++ name
            in
            ( p
                ++ var
                ++ " = \"eco.call\"() {function = @\""
                ++ kernelName
                ++ "\", musttail = false} : () -> !eco.value\n"
            , var
            , ctx1
            )

        ------------------------------------------
        -- DATA STRUCTURES (Easy)
        ------------------------------------------
        Opt.Unit ->
            let
                ( var, ctx1 ) =
                    freshVar ctx
            in
            ( p
                ++ var
                ++ " = \"eco.construct\"() {constructor = @\"Unit\", tag = 0 : i64, size = 0 : i64} : () -> !eco.value\n"
            , var
            , ctx1
            )

        Opt.Tuple _ a b maybeC ->
            let
                ( codeA, varA, ctx1 ) =
                    generateExpr ctx a

                ( codeB, varB, ctx2 ) =
                    generateExpr ctx1 b

                ( codeCs, varCs, ctx3 ) =
                    generateExprList ctx2 maybeC

                allVars : List String
                allVars =
                    varA :: varB :: varCs

                ( resultVar, ctx4 ) =
                    freshVar ctx3

                arity : Int
                arity =
                    List.length allVars

                ctorName : String
                ctorName =
                    "Tuple" ++ String.fromInt arity
            in
            ( codeA
                ++ codeB
                ++ codeCs
                ++ p
                ++ resultVar
                ++ " = \"eco.construct\"("
                ++ String.join ", " allVars
                ++ ") {constructor = @\""
                ++ ctorName
                ++ "\", tag = 0 : i64, size = "
                ++ String.fromInt arity
                ++ " : i64} : ("
                ++ String.join ", " (List.repeat arity "!eco.value")
                ++ ") -> !eco.value\n"
            , resultVar
            , ctx4
            )

        Opt.List _ items ->
            generateList ctx items

        Opt.Record fields ->
            generateRecord ctx fields

        Opt.TrackedRecord _ fields ->
            generateTrackedRecord ctx fields

        ------------------------------------------
        -- FUNCTIONS AND CALLS (Moderate)
        ------------------------------------------
        Opt.Function args body ->
            -- Anonymous function - create closure
            let
                ( var, ctx1 ) =
                    freshVar ctx

                arity : Int
                arity =
                    List.length args
            in
            ( p
                ++ "// TODO: Anonymous function with args: "
                ++ String.join ", " args
                ++ "\n"
                ++ p
                ++ var
                ++ " = \"eco.papCreate\"() {function = @\"anonymous\", arity = "
                ++ String.fromInt arity
                ++ " : i64, num_captured = 0 : i64} : () -> !eco.value\n"
            , var
            , ctx1
            )

        Opt.TrackedFunction locatedArgs body ->
            let
                args =
                    List.map A.toValue locatedArgs

                ( var, ctx1 ) =
                    freshVar ctx

                arity : Int
                arity =
                    List.length args
            in
            ( p
                ++ "// TODO: TrackedFunction with args: "
                ++ String.join ", " args
                ++ "\n"
                ++ p
                ++ var
                ++ " = \"eco.papCreate\"() {function = @\"anonymous\", arity = "
                ++ String.fromInt arity
                ++ " : i64, num_captured = 0 : i64} : () -> !eco.value\n"
            , var
            , ctx1
            )

        Opt.Call _ func args ->
            generateCall ctx func args

        Opt.TailCall name args ->
            let
                ( argsCode, argVars, ctx1 ) =
                    generateNamedArgs ctx args

                ( resultVar, ctx2 ) =
                    freshVar ctx1
            in
            ( argsCode
                ++ p
                ++ "\"eco.jump\"("
                ++ String.join ", " argVars
                ++ ") {join_point = 0} : ("
                ++ String.join ", " (List.repeat (List.length args) "!eco.value")
                ++ ") -> ()\n"
                ++ p
                ++ resultVar
                ++ " = \"eco.construct\"() {constructor = @\"Unreachable\", tag = 0 : i64, size = 0 : i64} : () -> !eco.value  // unreachable\n"
            , resultVar
            , ctx2
            )

        ------------------------------------------
        -- CONTROL FLOW (Moderate to Complex)
        ------------------------------------------
        Opt.If branches final ->
            generateIf ctx branches final

        Opt.Let def body ->
            generateLet ctx def body

        Opt.Destruct destructor body ->
            generateDestruct ctx destructor body

        Opt.Case scrutinee1 scrutinee2 decider jumps ->
            generateCase ctx scrutinee1 scrutinee2 decider jumps

        ------------------------------------------
        -- RECORD OPERATIONS (Moderate)
        ------------------------------------------
        Opt.Accessor _ fieldName ->
            let
                ( var, ctx1 ) =
                    freshVar ctx
            in
            ( p
                ++ "// TODO: Accessor function for ."
                ++ fieldName
                ++ "\n"
                ++ p
                ++ var
                ++ " = \"eco.papCreate\"() {function = @\"accessor_"
                ++ fieldName
                ++ "\", arity = 1 : i64, num_captured = 0 : i64} : () -> !eco.value\n"
            , var
            , ctx1
            )

        Opt.Access record _ fieldName ->
            let
                ( recordCode, recordVar, ctx1 ) =
                    generateExpr ctx record

                ( resultVar, ctx2 ) =
                    freshVar ctx1
            in
            ( recordCode
                ++ p
                ++ "// Access ."
                ++ fieldName
                ++ "\n"
                ++ p
                ++ resultVar
                ++ " = \"eco.project\"("
                ++ recordVar
                ++ ") {index = 0 : i64} : (!eco.value) -> !eco.value  // TODO: compute field index for "
                ++ fieldName
                ++ "\n"
            , resultVar
            , ctx2
            )

        Opt.Update _ record updates ->
            let
                ( recordCode, recordVar, ctx1 ) =
                    generateExpr ctx record

                ( resultVar, ctx2 ) =
                    freshVar ctx1

                fieldCount : Int
                fieldCount =
                    Dict.size updates
            in
            ( recordCode
                ++ p
                ++ "// TODO: Record update with "
                ++ String.fromInt fieldCount
                ++ " updated fields\n"
                ++ p
                ++ resultVar
                ++ " = \"eco.construct\"("
                ++ recordVar
                ++ ") {constructor = @\"RecordUpdate\", tag = 0 : i64, size = 1 : i64} : (!eco.value) -> !eco.value\n"
            , resultVar
            , ctx2
            )

        ------------------------------------------
        -- SPECIAL (Not supported)
        ------------------------------------------
        Opt.Shader _ _ _ ->
            let
                ( var, ctx1 ) =
                    freshVar ctx
            in
            ( p
                ++ "// ERROR: Shader not supported in native compilation\n"
                ++ p
                ++ var
                ++ " = \"eco.crash\"() {message = \"Shader not supported\"} : () -> !eco.value\n"
            , var
            , ctx1
            )



-- HELPER: Generate list of expressions


generateExprList : Context -> List Opt.Expr -> ( String, List String, Context )
generateExprList ctx exprs =
    List.foldl
        (\expr ( accCode, accVars, accCtx ) ->
            let
                ( code, var, newCtx ) =
                    generateExpr accCtx expr
            in
            ( accCode ++ code, accVars ++ [ var ], newCtx )
        )
        ( "", [], ctx )
        exprs



-- HELPER: Generate named args for tail call


generateNamedArgs : Context -> List ( Name.Name, Opt.Expr ) -> ( String, List String, Context )
generateNamedArgs ctx args =
    List.foldl
        (\( _, expr ) ( accCode, accVars, accCtx ) ->
            let
                ( code, var, newCtx ) =
                    generateExpr accCtx expr
            in
            ( accCode ++ code, accVars ++ [ var ], newCtx )
        )
        ( "", [], ctx )
        args



-- GENERATE LIST


generateList : Context -> List Opt.Expr -> ( String, String, Context )
generateList ctx items =
    let
        p : String
        p =
            pad ctx
    in
    case items of
        [] ->
            -- Empty list: Nil
            let
                ( var, ctx1 ) =
                    freshVar ctx
            in
            ( p
                ++ var
                ++ " = \"eco.construct\"() {constructor = @\"List_Nil\", tag = 0 : i64, size = 0 : i64} : () -> !eco.value\n"
            , var
            , ctx1
            )

        _ ->
            -- Build list from right to left: Cons(head, Cons(head2, ... Nil))
            let
                ( nilVar, ctx1 ) =
                    freshVar ctx

                nilCode : String
                nilCode =
                    p
                        ++ nilVar
                        ++ " = \"eco.construct\"() {constructor = @\"List_Nil\", tag = 0 : i64, size = 0 : i64} : () -> !eco.value\n"

                -- Fold from right, building up the list
                ( consCode, finalVar, finalCtx ) =
                    List.foldr
                        (\item ( accCode, tailVar, accCtx ) ->
                            let
                                ( itemCode, itemVar, ctx2 ) =
                                    generateExpr accCtx item

                                ( consVar, ctx3 ) =
                                    freshVar ctx2

                                consOp : String
                                consOp =
                                    pad ctx
                                        ++ consVar
                                        ++ " = \"eco.construct\"("
                                        ++ itemVar
                                        ++ ", "
                                        ++ tailVar
                                        ++ ") {constructor = @\"List_Cons\", tag = 1 : i64, size = 2 : i64} : (!eco.value, !eco.value) -> !eco.value\n"
                            in
                            ( itemCode ++ consOp ++ accCode, consVar, ctx3 )
                        )
                        ( "", nilVar, ctx1 )
                        items
            in
            ( nilCode ++ consCode
            , finalVar
            , finalCtx
            )



-- GENERATE RECORD


generateRecord : Context -> Dict.Dict String Name.Name Opt.Expr -> ( String, String, Context )
generateRecord ctx fields =
    let
        p : String
        p =
            pad ctx

        fieldList : List ( Name.Name, Opt.Expr )
        fieldList =
            Dict.toList compare fields

        ( fieldsCode, fieldVars, ctx1 ) =
            List.foldl
                (\( _, expr ) ( accCode, accVars, accCtx ) ->
                    let
                        ( code, var, newCtx ) =
                            generateExpr accCtx expr
                    in
                    ( accCode ++ code, accVars ++ [ var ], newCtx )
                )
                ( "", [], ctx )
                fieldList

        ( resultVar, ctx2 ) =
            freshVar ctx1

        arity : Int
        arity =
            List.length fieldList

        fieldNames : String
        fieldNames =
            fieldList
                |> List.map Tuple.first
                |> String.join ", "
    in
    ( fieldsCode
        ++ p
        ++ "// Record with fields: "
        ++ fieldNames
        ++ "\n"
        ++ p
        ++ resultVar
        ++ " = \"eco.construct\"("
        ++ String.join ", " fieldVars
        ++ ") {constructor = @\"Record\", tag = 0 : i64, size = "
        ++ String.fromInt arity
        ++ " : i64} : ("
        ++ String.join ", " (List.repeat arity "!eco.value")
        ++ ") -> !eco.value\n"
    , resultVar
    , ctx2
    )


generateTrackedRecord : Context -> Dict.Dict String (A.Located Name.Name) Opt.Expr -> ( String, String, Context )
generateTrackedRecord ctx fields =
    let
        p : String
        p =
            pad ctx

        fieldList : List ( A.Located Name.Name, Opt.Expr )
        fieldList =
            Dict.toList A.compareLocated fields

        ( fieldsCode, fieldVars, ctx1 ) =
            List.foldl
                (\( _, expr ) ( accCode, accVars, accCtx ) ->
                    let
                        ( code, var, newCtx ) =
                            generateExpr accCtx expr
                    in
                    ( accCode ++ code, accVars ++ [ var ], newCtx )
                )
                ( "", [], ctx )
                fieldList

        ( resultVar, ctx2 ) =
            freshVar ctx1

        arity : Int
        arity =
            List.length fieldList

        fieldNames : String
        fieldNames =
            fieldList
                |> List.map (Tuple.first >> A.toValue)
                |> String.join ", "
    in
    ( fieldsCode
        ++ p
        ++ "// TrackedRecord with fields: "
        ++ fieldNames
        ++ "\n"
        ++ p
        ++ resultVar
        ++ " = \"eco.construct\"("
        ++ String.join ", " fieldVars
        ++ ") {constructor = @\"Record\", tag = 0 : i64, size = "
        ++ String.fromInt arity
        ++ " : i64} : ("
        ++ String.join ", " (List.repeat arity "!eco.value")
        ++ ") -> !eco.value\n"
    , resultVar
    , ctx2
    )



-- GENERATE CALL


generateCall : Context -> Opt.Expr -> List Opt.Expr -> ( String, String, Context )
generateCall ctx func args =
    let
        p : String
        p =
            pad ctx
    in
    case func of
        Opt.VarGlobal _ global ->
            -- Direct call to known function
            let
                ( argsCode, argVars, ctx1 ) =
                    generateExprList ctx args

                ( resultVar, ctx2 ) =
                    freshVar ctx1

                funcName : String
                funcName =
                    globalToMLIRName global

                argCount : Int
                argCount =
                    List.length args
            in
            ( argsCode
                ++ p
                ++ resultVar
                ++ " = \"eco.call\"("
                ++ String.join ", " argVars
                ++ ") {function = @\""
                ++ funcName
                ++ "\", musttail = false} : ("
                ++ String.join ", " (List.repeat argCount "!eco.value")
                ++ ") -> !eco.value\n"
            , resultVar
            , ctx2
            )

        Opt.VarLocal name ->
            -- Call to local variable (closure)
            let
                ( argsCode, argVars, ctx1 ) =
                    generateExprList ctx args

                ( resultVar, ctx2 ) =
                    freshVar ctx1

                allArgs : List String
                allArgs =
                    ("%" ++ name) :: argVars

                argCount : Int
                argCount =
                    List.length allArgs
            in
            ( argsCode
                ++ p
                ++ resultVar
                ++ " = \"eco.papExtend\"("
                ++ String.join ", " allArgs
                ++ ") : ("
                ++ String.join ", " (List.repeat argCount "!eco.value")
                ++ ") -> !eco.value\n"
            , resultVar
            , ctx2
            )

        _ ->
            -- General case: evaluate function, then call
            let
                ( funcCode, funcVar, ctx1 ) =
                    generateExpr ctx func

                ( argsCode, argVars, ctx2 ) =
                    generateExprList ctx1 args

                ( resultVar, ctx3 ) =
                    freshVar ctx2

                allArgs : List String
                allArgs =
                    funcVar :: argVars

                argCount : Int
                argCount =
                    List.length allArgs
            in
            ( funcCode
                ++ argsCode
                ++ p
                ++ resultVar
                ++ " = \"eco.papExtend\"("
                ++ String.join ", " allArgs
                ++ ") : ("
                ++ String.join ", " (List.repeat argCount "!eco.value")
                ++ ") -> !eco.value\n"
            , resultVar
            , ctx3
            )



-- GENERATE IF


generateIf : Context -> List ( Opt.Expr, Opt.Expr ) -> Opt.Expr -> ( String, String, Context )
generateIf ctx branches final =
    let
        p : String
        p =
            pad ctx

        ( resultVar, ctx1 ) =
            freshVar ctx
    in
    case branches of
        [] ->
            -- No branches, just the else
            generateExpr ctx final

        ( cond, thenBranch ) :: restBranches ->
            let
                ( condCode, condVar, ctx2 ) =
                    generateExpr ctx1 cond

                ( thenCode, thenVar, ctx3 ) =
                    generateExpr ctx2 thenBranch

                ( elseCode, elseVar, ctx4 ) =
                    generateIf ctx3 restBranches final
            in
            ( condCode
                ++ p
                ++ "// TODO: If-then-else (needs scf.if or cf.cond_br)\n"
                ++ p
                ++ "// condition: "
                ++ condVar
                ++ "\n"
                ++ thenCode
                ++ elseCode
                ++ p
                ++ "// TODO: Select between "
                ++ thenVar
                ++ " and "
                ++ elseVar
                ++ " based on "
                ++ condVar
                ++ "\n"
            , elseVar
            , ctx4
            )



-- GENERATE LET


generateLet : Context -> Opt.Def -> Opt.Expr -> ( String, String, Context )
generateLet ctx def body =
    let
        p : String
        p =
            pad ctx
    in
    case def of
        Opt.Def _ name expr ->
            let
                ( exprCode, exprVar, ctx1 ) =
                    generateExpr ctx expr

                -- The binding creates a new SSA variable with the given name
                bindCode : String
                bindCode =
                    p ++ "// let " ++ name ++ " = ...\n"

                -- For now, we'll use a simple alias comment
                -- In real MLIR, we'd need to properly thread the variable
                ( bodyCode, bodyVar, ctx2 ) =
                    generateExpr ctx1 body
            in
            ( exprCode
                ++ bindCode
                ++ p
                ++ "%"
                ++ name
                ++ " = \"eco.construct\"("
                ++ exprVar
                ++ ") {constructor = @\"Alias\", tag = 0 : i64, size = 1 : i64} : (!eco.value) -> !eco.value  // alias binding\n"
                ++ bodyCode
            , bodyVar
            , ctx2
            )

        Opt.TailDef _ name locatedArgs expr ->
            let
                args : List Name.Name
                args =
                    List.map A.toValue locatedArgs
            in
            ( p
                ++ "// TODO: Local tail-recursive definition: "
                ++ name
                ++ " with args: "
                ++ String.join ", " args
                ++ "\n"
                ++ p
                ++ "\"eco.joinpoint\"() ({\n"
                ++ p
                ++ "  // joinpoint body\n"
                ++ p
                ++ "}, {\n"
                ++ p
                ++ "  // continuation\n"
                ++ p
                ++ "}) {id = 0} : () -> ()\n"
            , "%todo_taildef"
            , ctx
            )



-- GENERATE DESTRUCT


generateDestruct : Context -> Opt.Destructor -> Opt.Expr -> ( String, String, Context )
generateDestruct ctx (Opt.Destructor name path) body =
    let
        p : String
        p =
            pad ctx

        ( pathCode, pathVar, ctx1 ) =
            generatePath ctx path

        ( bodyCode, bodyVar, ctx2 ) =
            generateExpr ctx1 body
    in
    ( pathCode
        ++ p
        ++ "%"
        ++ name
        ++ " = \"eco.construct\"("
        ++ pathVar
        ++ ") {constructor = @\"Alias\", tag = 0 : i64, size = 1 : i64} : (!eco.value) -> !eco.value  // destructure binding\n"
        ++ bodyCode
    , bodyVar
    , ctx2
    )


generatePath : Context -> Opt.Path -> ( String, String, Context )
generatePath ctx path =
    let
        p : String
        p =
            pad ctx
    in
    case path of
        Opt.Root name ->
            ( "", "%" ++ name, ctx )

        Opt.Index index subPath ->
            let
                ( subCode, subVar, ctx1 ) =
                    generatePath ctx subPath

                ( resultVar, ctx2 ) =
                    freshVar ctx1

                idx : Int
                idx =
                    Index.toMachine index
            in
            ( subCode
                ++ p
                ++ resultVar
                ++ " = \"eco.project\"("
                ++ subVar
                ++ ") {index = "
                ++ String.fromInt idx
                ++ " : i64} : (!eco.value) -> !eco.value\n"
            , resultVar
            , ctx2
            )

        Opt.Field name subPath ->
            let
                ( subCode, subVar, ctx1 ) =
                    generatePath ctx subPath

                ( resultVar, ctx2 ) =
                    freshVar ctx1
            in
            ( subCode
                ++ p
                ++ "// Project field: "
                ++ name
                ++ "\n"
                ++ p
                ++ resultVar
                ++ " = \"eco.project\"("
                ++ subVar
                ++ ") {index = 0 : i64} : (!eco.value) -> !eco.value  // TODO: compute field index for "
                ++ name
                ++ "\n"
            , resultVar
            , ctx2
            )

        Opt.Unbox subPath ->
            -- Unbox is identity for our purposes
            generatePath ctx subPath

        Opt.ArrayIndex idx subPath ->
            let
                ( subCode, subVar, ctx1 ) =
                    generatePath ctx subPath

                ( resultVar, ctx2 ) =
                    freshVar ctx1
            in
            ( subCode
                ++ p
                ++ resultVar
                ++ " = \"eco.project\"("
                ++ subVar
                ++ ") {index = "
                ++ String.fromInt idx
                ++ " : i64} : (!eco.value) -> !eco.value  // array index\n"
            , resultVar
            , ctx2
            )



-- GENERATE CASE


generateCase : Context -> Name.Name -> Name.Name -> Opt.Decider Opt.Choice -> List ( Int, Opt.Expr ) -> ( String, String, Context )
generateCase ctx scrutinee1 scrutinee2 decider jumps =
    let
        p : String
        p =
            pad ctx

        ( resultVar, ctx1 ) =
            freshVar ctx

        jumpCount : Int
        jumpCount =
            List.length jumps
    in
    ( p
        ++ "// TODO: Case expression on %"
        ++ scrutinee1
        ++ " (temp: %"
        ++ scrutinee2
        ++ ")\n"
        ++ p
        ++ "// Decision tree with "
        ++ String.fromInt jumpCount
        ++ " jump targets\n"
        ++ p
        ++ "\"eco.case\"(%"
        ++ scrutinee1
        ++ ") ({\n"
        ++ p
        ++ "  // TODO: Generate decision tree\n"
        ++ p
        ++ "  \"eco.return\"(%"
        ++ scrutinee1
        ++ ") : (!eco.value) -> ()\n"
        ++ p
        ++ "}) {tags = [0]} : (!eco.value) -> ()\n"
        ++ p
        ++ resultVar
        ++ " = \"eco.construct\"() {constructor = @\"CaseResult\", tag = 0 : i64, size = 0 : i64} : () -> !eco.value  // TODO: actual case result\n"
    , resultVar
    , ctx1
    )



-- HELPERS


type alias Graph =
    Dict.Dict (List String) Opt.Global Opt.Node


canonicalToMLIRName : IO.Canonical -> String
canonicalToMLIRName (IO.Canonical _ moduleName) =
    String.replace "." "_" moduleName


globalToMLIRName : Opt.Global -> String
globalToMLIRName (Opt.Global home name) =
    canonicalToMLIRName home ++ "_" ++ sanitizeName name


sanitizeName : String -> String
sanitizeName name =
    -- Replace operators and special chars with safe names
    name
        |> String.replace "+" "_plus_"
        |> String.replace "-" "_minus_"
        |> String.replace "*" "_star_"
        |> String.replace "/" "_slash_"
        |> String.replace "<" "_lt_"
        |> String.replace ">" "_gt_"
        |> String.replace "=" "_eq_"
        |> String.replace "&" "_amp_"
        |> String.replace "|" "_pipe_"
        |> String.replace "!" "_bang_"
        |> String.replace "?" "_question_"
        |> String.replace ":" "_colon_"
        |> String.replace "." "_dot_"
        |> String.replace "$" "_dollar_"


boolToString : Bool -> String
boolToString b =
    if b then
        "true"

    else
        "false"


escapeString : String -> String
escapeString s =
    "\""
        ++ String.foldr
            (\c acc ->
                (case c of
                    '"' ->
                        "\\\""

                    '\\' ->
                        "\\\\"

                    '\n' ->
                        "\\n"

                    '\t' ->
                        "\\t"

                    '\u{000D}' ->
                        "\\r"

                    _ ->
                        String.fromChar c
                )
                    ++ acc
            )
            ""
            s
        ++ "\""
