module Compiler.Generate.CodeGen.MLIR exposing (backend)

import Compiler.AST.Optimized as Opt
import Compiler.Data.Name as Name
import Compiler.Elm.ModuleName as ModuleName
import Compiler.Generate.CodeGen as CodeGen
import Compiler.Generate.Mode as Mode
import Data.Map as Dict
import System.TypeCheck.IO as IO


backend : CodeGen.CodeGen
backend =
    { generate =
        \config ->
            CodeGen.TextOutput <|
                generateModule config.mode config.graph config.mains
    , generateForRepl =
        \_ ->
            -- MLIR REPL would need compilation + execution
            CodeGen.TextOutput "// MLIR REPL not yet implemented\n"
    , generateForReplEndpoint =
        \_ ->
            CodeGen.TextOutput "// MLIR REPL endpoint not yet implemented\n"
    }



-- GENERATE MODULE


generateModule : Mode.Mode -> Opt.GlobalGraph -> CodeGen.Mains -> String
generateModule mode (Opt.GlobalGraph graph _) mains =
    let
        header : String
        header =
            "// Generated by Guida MLIR backend\n"
                ++ "// This is a skeleton implementation\n\n"
                ++ "module {\n"

        footer : String
        footer =
            "}\n"

        mainFuncs : String
        mainFuncs =
            Dict.foldr ModuleName.compareCanonical (generateMain mode graph) "" mains
    in
    header ++ mainFuncs ++ footer



-- GENERATE MAIN


generateMain : Mode.Mode -> Graph -> IO.Canonical -> Opt.Main -> String -> String
generateMain mode graph home main acc =
    let
        funcName : String
        funcName =
            canonicalToMLIRName home ++ "_main"
    in
    case main of
        Opt.Static ->
            acc
                ++ "  // Static main: "
                ++ funcName
                ++ "\n"
                ++ "  func.func @"
                ++ funcName
                ++ "() -> i64 {\n"
                ++ "    %0 = arith.constant 0 : i64\n"
                ++ "    return %0 : i64\n"
                ++ "  }\n\n"

        Opt.Dynamic _ expr ->
            acc
                ++ "  // Dynamic main: "
                ++ funcName
                ++ "\n"
                ++ "  func.func @"
                ++ funcName
                ++ "() -> i64 {\n"
                ++ generateExpr mode 2 expr
                ++ "    %result = arith.constant 0 : i64\n"
                ++ "    return %result : i64\n"
                ++ "  }\n\n"



-- GENERATE EXPRESSION


generateExpr : Mode.Mode -> Int -> Opt.Expr -> String
generateExpr mode indent expr =
    let
        pad : String
        pad =
            String.repeat indent "  "
    in
    case expr of
        Opt.Bool _ value ->
            pad ++ "// Bool: " ++ boolToString value ++ "\n"

        Opt.Chr _ value ->
            pad ++ "// Chr: " ++ value ++ "\n"

        Opt.Str _ value ->
            pad ++ "// Str: " ++ escapeString value ++ "\n"

        Opt.Int _ value ->
            pad ++ "// Int: " ++ String.fromInt value ++ "\n"

        Opt.Float _ value ->
            pad ++ "// Float: " ++ String.fromFloat value ++ "\n"

        Opt.VarLocal name ->
            pad ++ "// VarLocal: " ++ name ++ "\n"

        Opt.TrackedVarLocal _ name ->
            pad ++ "// TrackedVarLocal: " ++ name ++ "\n"

        Opt.VarGlobal _ (Opt.Global home name) ->
            pad ++ "// VarGlobal: " ++ canonicalToMLIRName home ++ "." ++ name ++ "\n"

        Opt.VarEnum _ (Opt.Global home name) _ ->
            pad ++ "// VarEnum: " ++ canonicalToMLIRName home ++ "." ++ name ++ "\n"

        Opt.VarBox _ _ ->
            pad ++ "// VarBox\n"

        Opt.VarCycle _ home name ->
            pad ++ "// VarCycle: " ++ canonicalToMLIRName home ++ "." ++ name ++ "\n"

        Opt.VarDebug _ name _ _ ->
            pad ++ "// VarDebug: " ++ name ++ "\n"

        Opt.VarKernel _ home name ->
            pad ++ "// VarKernel: " ++ home ++ "." ++ name ++ "\n"

        Opt.List _ exprs ->
            pad
                ++ "// List with "
                ++ String.fromInt (List.length exprs)
                ++ " elements\n"
                ++ String.concat (List.map (generateExpr mode (indent + 1)) exprs)

        Opt.Function args body ->
            pad
                ++ "// Function with args: "
                ++ String.join ", " args
                ++ "\n"
                ++ generateExpr mode (indent + 1) body

        Opt.TrackedFunction args body ->
            pad
                ++ "// TrackedFunction with "
                ++ String.fromInt (List.length args)
                ++ " args\n"
                ++ generateExpr mode (indent + 1) body

        Opt.Call _ func args ->
            pad
                ++ "// Call with "
                ++ String.fromInt (List.length args)
                ++ " args\n"
                ++ generateExpr mode (indent + 1) func
                ++ String.concat (List.map (generateExpr mode (indent + 1)) args)

        Opt.TailCall name args ->
            pad
                ++ "// TailCall: "
                ++ name
                ++ " with "
                ++ String.fromInt (List.length args)
                ++ " args\n"

        Opt.If branches final ->
            pad
                ++ "// If with "
                ++ String.fromInt (List.length branches)
                ++ " branches\n"
                ++ generateExpr mode (indent + 1) final

        Opt.Let def body ->
            pad
                ++ "// Let\n"
                ++ generateDef mode (indent + 1) def
                ++ generateExpr mode (indent + 1) body

        Opt.Destruct _ body ->
            pad ++ "// Destruct\n" ++ generateExpr mode (indent + 1) body

        Opt.Case _ _ _ _ ->
            pad ++ "// Case expression\n"

        Opt.Accessor _ name ->
            pad ++ "// Accessor: ." ++ name ++ "\n"

        Opt.Access record _ name ->
            pad ++ "// Access: ." ++ name ++ "\n" ++ generateExpr mode (indent + 1) record

        Opt.Update _ record _ ->
            pad ++ "// Update\n" ++ generateExpr mode (indent + 1) record

        Opt.Record fields ->
            pad
                ++ "// Record with "
                ++ String.fromInt (Dict.size fields)
                ++ " fields\n"

        Opt.TrackedRecord _ fields ->
            pad
                ++ "// TrackedRecord with "
                ++ String.fromInt (Dict.size fields)
                ++ " fields\n"

        Opt.Unit ->
            pad ++ "// Unit\n"

        Opt.Tuple _ a b cs ->
            pad
                ++ "// Tuple"
                ++ String.fromInt (2 + List.length cs)
                ++ "\n"
                ++ generateExpr mode (indent + 1) a
                ++ generateExpr mode (indent + 1) b
                ++ String.concat (List.map (generateExpr mode (indent + 1)) cs)

        Opt.Shader _ _ _ ->
            pad ++ "// Shader (not supported in MLIR backend)\n"



-- GENERATE DEF


generateDef : Mode.Mode -> Int -> Opt.Def -> String
generateDef mode indent def =
    let
        pad : String
        pad =
            String.repeat indent "  "
    in
    case def of
        Opt.Def _ name expr ->
            pad ++ "// Def: " ++ name ++ "\n" ++ generateExpr mode (indent + 1) expr

        Opt.TailDef _ name args expr ->
            pad
                ++ "// TailDef: "
                ++ name
                ++ " with "
                ++ String.fromInt (List.length args)
                ++ " args\n"
                ++ generateExpr mode (indent + 1) expr



-- HELPERS


type alias Graph =
    Dict.Dict (List String) Opt.Global Opt.Node


canonicalToMLIRName : IO.Canonical -> String
canonicalToMLIRName (IO.Canonical _ moduleName) =
    String.replace "." "_" moduleName


boolToString : Bool -> String
boolToString b =
    if b then
        "true"

    else
        "false"


escapeString : String -> String
escapeString s =
    "\""
        ++ String.foldr
            (\c acc ->
                (case c of
                    '"' ->
                        "\\\""

                    '\\' ->
                        "\\\\"

                    '\n' ->
                        "\\n"

                    '\t' ->
                        "\\t"

                    _ ->
                        String.fromChar c
                )
                    ++ acc
            )
            ""
            s
        ++ "\""
