//===- eco_entry.cpp - Entry point wrapper for AOT-compiled binaries ------===//
//
// Provides the C main() for executables produced by eco-boot. Initializes the
// Eco runtime (GC, effect managers, globals) then calls the Elm program's
// main function (renamed to eco_main by eco-boot to avoid symbol clash).
//
//===----------------------------------------------------------------------===//

#include "../allocator/Allocator.hpp"

extern "C" {

// Generated by EcoToLLVM pass when eco.global ops are present.
// Declared weak so modules without globals link correctly.
__attribute__((weak)) void __eco_init_globals();

// The Elm main function, renamed from "main" to "eco_main" by eco-boot
// during LLVM IR emission to avoid conflict with this C main.
int64_t eco_main();

// Effect manager registration (from ElmKernel_EffectRegistry).
void eco_register_all_effect_managers();

} // extern "C"

int main(int argc, char **argv) {
    // Initialize the generational GC and thread-local heap.
    Elm::Allocator::instance().initialize();
    Elm::Allocator::instance().initThread();

    // Register global variables as GC roots (if the module has any).
    if (__eco_init_globals)
        __eco_init_globals();

    // Register effect managers (Time, Http, etc.) with the scheduler.
    eco_register_all_effect_managers();

    // Run the Elm program.
    int64_t result = eco_main();

    // Cleanup thread-local allocator state.
    Elm::Allocator::instance().cleanupThread();

    return static_cast<int>(result);
}
